### ISSUE TITLE
Cthulhu can be killed

### ISSUE THREAD

**Issue by 19DollarFortniteGiftcard** [donkeyrat/HiddenUnits#6]
1) Can be killed after taking enough damage (It took a few minutes for 200 billys to kill him)

2) One punch man does insta kill Cthulhu (He needs to use his teleport to reach him)

3) Battle does not end when Cthulhu dies (But he cant move or attack, he becomes a ragdoll and eyes turn into X, units still attack him and can still be possessed)

![Screenshot 2024-11-29 082158](https://github.com/user-attachments/assets/7ee266a8-f364-489e-8e02-b636564f65cd)

**Comment by donkeyrat** [comment]
He's meant to be killable, the only bug here is the battle not ending.
